apiVersion: v1
kind: Service
metadata:
  labels:
    app: qqaclient
  name: qqaclient
  namespace: default
spec:
  ports:
  - name: http-tf-serving
    port: 5999
    targetPort: 5999
  selector:
    app: qqaclient
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qqaclient
  name: qqaclient
  namespace: default
spec:
  selector:
    matchLabels:
      app: qqaclient
  template:
    metadata:
      labels:
        app: qqaclient
        version: v1
    spec:
      serviceAccount: quasiqa-sa
      containers:
      - args:
        - --http=:5999
        env:
        - name: BIGQUERY_DF
          value: "integrated-hawk-323110.qqa_text.qqatext_df"
        - name: MODEL_TYPE
          value: "bert"
        - name: PUBSUB_TOPIC
          value: "quasiQa-kb-notify"
        - name: GCLOUD_PROJECT
          value: "integrated-hawk-323110"
        - name: BERT_MODEL
          value: "bert_model_choice"
        - name: T5_MODEL
          value: "mrm8488/t5-base-finetuned-summarize-news"
        - name: FAST_T5_MODEL
          value: "t5-small"
        image: us.gcr.io/integrated-hawk-323110/quasiqa:9ed60dd
        imagePullPolicy: Always
        name: qqaclient
        ports:
        - containerPort: 5999
